### ISSUE TITLE
Add geographic covariate code to inventory

### ISSUE THREAD

**Issue by Spatiotemporal-Exposures-and-Toxicology** [Spatiotemporal-Exposures-and-Toxicology/NRTAPmodel#175]

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
Please add any complete or potentially usable functions for covariate calculations to the Excel inventory on the project teams channel: NRT-AP-Model_Covariate_Code_Inventory.xlsx.

If nothing is applicable, then it is all good - please still check off.

- [ ] @eva0marques 
- [ ] @sigmafelix 
- [ ] @larapclark 
- [ ] @mitchellmanware 
- [ ] @MAKassien 
- [ ] @dzilber 
- [ ] @dawranadeep 
- [ ] @Spatiotemporal-Exposures-and-Toxicology

**Comment by eva0marques** [comment]
I added my code paths in the "Notes" column.
