### ISSUE TITLE
Download and create NEI non-point source data

### ISSUE THREAD

**Issue by dawranadeep** [Spatiotemporal-Exposures-and-Toxicology/NRTAPmodel#199]

**Comment by dawranadeep** [comment]
1) Using county-wise emission data instead from NEI 2017 and 2020.
2) Download code is at https://github.com/Spatiotemporal-Exposures-and-Toxicology/NRTAPmodel/blob/download_aadt/R/download_aadt.txt

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
- [ ] @dawranadeep  Extract year and county to x,y location 
- [ ] @sigmafelix refactor into R/calc_covariates.R

**Comment by mitchellmanware** [comment]
@sigmafelix 

Related- I have covariate calculation functions for narr and geos with tests almost complete. I will clone branch `isong-calc-covars`, contribute my functions and tests, and then pull request back to your branch.

Should be complete by tomorrow (1/5).

**Comment by eva0marques** [comment]
@dawranadeep @sigmafelix 
I am renaming /Volumes/set/Projects/NRT-AP-Model/input/NEI/aadt2020/onroad123.csv as /Volumes/set/Projects/NRT-AP-Model/input/NEI/aadt2020/onroad_123.csv. It is necessary for the data path dictionary in /inst/extdata/downloaded_files_metadata.csv and I guess it is an unwanted error.

**Comment by sigmafelix** [comment]
@eva0marques Is the metadata csv file only for our pipeline or for general use? If the latter is the case, I suggest keeping the original file name in the zip file as the decision will affect future maintenance load to change file names accordingly (i.e., in unzipping part). As NEI/AADT data will be maintained in the separate year's directories, we will be fine to use the file names as they are.
