### ISSUE TITLE
Linting bypass for cyclomatic complexity cases

### ISSUE THREAD

**Issue by sigmafelix** [Spatiotemporal-Exposures-and-Toxicology/NRTAPmodel#208]
- Several functions, most of which are for download functions, are not expected to pass lint checks as there are many `if ... else ...` statements or `methods::is` calls, etc. To bypass this, one can manually wrap a function with `# nolint start` and `# nolint end` ([Reference](https://lintr.r-lib.org/reference/exclude.html)), for example:

#### Before
```r
download_something <- function () {
    if (...) {download.file(...)} else { return(NULL) }
}
```

#### After
```r
# nolint start
download_something <- function () {
    if (...) {download.file(...)} else { return(NULL) }
}
# nolint end
```

It should be noted that bypassing should be allowed to functions with cyclomatic complexity only. Codes in general should abide by the general style guidance from linters. To see whether there is cyclomatic complexity, please run linter this code in RStudio Addins > Lint current file

<img width="292" alt="image" src="https://github.com/Spatiotemporal-Exposures-and-Toxicology/NRTAPmodel/assets/25448786/d2a8e87b-e35b-43bb-b19e-fdb6b6f88689">

After linting, a tab named "Markers" will appear at the third quadrant (given that your RStudio is in default panel configurations).

**Comment by sigmafelix** [comment]
This issue is moved to "Wiki" section.

**Comment by mitchellmanware** [comment]
@sigmafelix 

Another way to implement `#nolint` on the data download functions is with a `.lintr` configuration file. The configuration file will allow us to "exclude" specific lines/sections of code in the `download...data.R` functions from one or more linters, in this case the `cyclocomp_linter`.

Using this method we can ensure that all other linters are applied to the download functions, and avoid potentially confusing `#nolint start/end` lines of code within the `R/` folder.

I have explored the `.lintr` configuration file on branch mm_download_function_enhancements_1117, and applied it to the GEOS-CF, GMTED, and NCEP NARR data download functions.

https://cran.r-project.org/web/packages/lintr/vignettes/lintr.html

**Comment by sigmafelix** [comment]
@mitchellmanware Sounds good. I will delete the obsolete wiki page.
