### ISSUE TITLE
Standardize relative/absolute path reference with a script?

### ISSUE THREAD

**Issue by sigmafelix** [Spatiotemporal-Exposures-and-Toxicology/NRTAPmodel#214]
@Spatiotemporal-Exposures-and-Toxicology 

I have been writing path reference in covariate calculation functions with the assumption of the working directory being the root directory of the project. Considering that this project will be packaged and the large datasets will be stored in ddn at the moment, I think it would be helpful for all to have a configuration script that assigns the data directories (`./input`) with one or two user inputs (e.g., user names for ddn reference). This issue can also be related to writing a pipeline with `targets`.

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@sigmafelix sounds like a good idea. I'd like to learn more about this technique.

**Comment by sigmafelix** [comment]
We could control reused elements in `_targets.R` file for `targets` pipeline. For tests, using `testthat::test_path()` will be helpful to run tests locally and in GitHub CI Action without manually changing path strings. I will close this issue.
