### ISSUE TITLE
Download and process NOAA HMS Smoke data

### ISSUE THREAD

**Issue by mitchellmanware** [Spatiotemporal-Exposures-and-Toxicology/NRTAPmodel#250]

**Comment by mitchellmanware** [comment]
- [ ] Create `calc_hms` function
  - [ ] May require a `process_hms` function to separate light, medium, and heavy layers
- [ ] Download data
- [ ] Calculate covariates

**Comment by sigmafelix** [comment]
@mitchellmanware 
FYI, I downloaded and put a zip file with all HMS daily zips in [project root]/input/HMS_Smoke in DDN. The directory name might need to be changed. Please let me know if there is a problem with the zip file I've put.

**Comment by mitchellmanware** [comment]
@sigmafelix 

Thanks. I will change it if needed. Although the data is downloaded, I do not believe there is a calculation function for this data set. Is that correct?

**Comment by sigmafelix** [comment]
@mitchellmanware Correct. There is no calculation function yet. I think the function will perform a vector-vector overlay if we don't rasterize the smoke polygons. Rasterization script was written for my PEGS project last month, so I will share it here if it would be helpful.

**Comment by mitchellmanware** [comment]
@sigmafelix 

As it is natively vector data maybe better to perform vector-vector overlay. Should be a straightforward function- I will work on it next week.

**Comment by mitchellmanware** [comment]
NOAA HMS Wildfire Smoke Data missing for July 7, 2019

https://satepsanone.nesdis.noaa.gov/pub/FIRE/web/HMS/Smoke_Polygons/Shapefile/2019/07/hms_smoke20190710.zip

**Comment by mitchellmanware** [comment]
Update- January 12

Responses from NOAA representative
- No wildfire smoke plumes detected for December 31, 2018
- Download URL for July 10, 2019 was broken, but has been restored.

Covariate progress

- [ ] Include provision for no wildfire smoke plumes
- [ ] Re-run calculation with full temporal range to ensure proper functioning

**Comment by mitchellmanware** [comment]
NOAA HMS covariates calculated and available in `NRT-AP-Model/output/NRTAP_Covar_HMS.rds`. Raw data available in `NRT-AP-Model/input/HMS_smoke/hms_smoke_2018_2022.zip` ( @sigmafelix zip file updated to included restored July 10, 2019 data).

`process_hms` and `calc_hms` functions accessible on branch mm-calc-functions. Unit tests to be written based on spatial subsample by @eva0marques. Other tweaks may be necessary to adapt function, but closing issue as covariates are calculated.
