### ISSUE TITLE
Final Model Output Unit Test - Stats Test - Test that the variances are non-negative

### ISSUE THREAD

**Issue by Spatiotemporal-Exposures-and-Toxicology** [Spatiotemporal-Exposures-and-Toxicology/NRTAPmodel#41]

**Comment by dawranadeep** [comment]
There is a skeleton code at the location below:

https://github.com/Spatiotemporal-Exposures-and-Toxicology/NRTAPmodel/commit/487fb9d5e26c440eb30d45b747b83221c2719c8a


Thanks,
Ranadeep
