### ISSUE TITLE
AQS data: Explore spatiotemporal trends

### ISSUE THREAD

**Issue by MAKassien** [Spatiotemporal-Exposures-and-Toxicology/NRTAPmodel#9]
1. Yearly and seasonal averages across the whole country - are there any changes in temporal trends between 2019-2022?
2. What are the spatial trends? Could these inform covariate selection?

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@MAKassien @sigmafelix can we close this issue and the AQS Data milestone?

**Comment by sigmafelix** [comment]
@Spatiotemporal-Exposures-and-Toxicology I agree on closing this issue. Thank you!

**Comment by MAKassien** [comment]
I agree too!
